// ==UserScript==
// @name         Outlook Web — minimal calendar (Omarchy)
// @namespace    omarchy
// @version      @VERSION@
// @description  Strips OWA chrome, compresses the day scale, rebuilds a minimal action bar, and retints the whole app to the current Omarchy theme.
// @license      MIT
// @homepageURL  https://github.com/pedrosekine/owa-minimal
// @updateURL    http://127.0.0.1:8787/owa-minimal.user.js
// @downloadURL  http://127.0.0.1:8787/owa-minimal.user.js
// @match        https://outlook.office.com/*
// @match        https://outlook.office365.com/*
// @match        https://outlook.cloud.microsoft/*
// @run-at       document-start
// @grant        GM_xmlhttpRequest
// @grant        GM.xmlHttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @connect      127.0.0.1
// @connect      localhost
// ==/UserScript==
//
// GENERATED by ./build.sh from extension/core.js and userscript/env.js.
// Edit those, not this file. The Chrome extension in extension/ is the
// primary way to install this; the userscript remains for managers that
// can install from a URL, and for the local update server.
