#!/usr/bin/env python3
"""Serve the current Omarchy palette to foresight (the Outlook Web calendar reduction).

The palette is read fresh on every request rather than cached or
regenerated by a theme-set hook, so switching themes needs no extra
wiring: the next poll simply sees the new colours.

Bound to loopback only. Serves exactly one file's worth of data.
"""

import configparser
import http.server
import json
import os
import re
import subprocess
import time
import tomllib

THEME = os.path.expanduser("~/.local/state/omarchy/current/theme/colors.toml")
HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPT = os.path.join(HERE, "foresight.user.js")
# The pre-rename path is kept so an install from before 5.0 still reaches the
# file once, and picks up the new @updateURL from its header.
SCRIPT_ROUTES = ("/foresight.user.js", "/owa-minimal.user.js")
HOST = "127.0.0.1"
PORT = 8787


# Request counters, exposed at /stats. Cheaper than turning on access
# logging for a 3-second poll, and it answers the only question worth asking
# when theming looks dead: is the userscript reaching us at all?
STATS = {"theme": 0, "script": 0, "other": 0, "last": None}


GTK_INI = os.path.expanduser("~/.config/gtk-3.0/settings.ini")
FONT_CACHE = {"at": 0.0, "family": ""}


def ui_font():
    """The desktop's UI font family, as GTK apps (and Chromium's own frame)
    draw it. Measured 2026-09-17: Chromium under Hyprland resolves CSS
    `system-ui` through fontconfig to Liberation Sans, not to this setting,
    so the family has to be named to the page explicitly."""
    now = time.monotonic()
    if now - FONT_CACHE["at"] < 10:
        return FONT_CACHE["family"]
    name = ""
    try:
        name = subprocess.run(
            ["gsettings", "get", "org.gnome.desktop.interface", "font-name"],
            capture_output=True, text=True, timeout=2).stdout.strip().strip("'\"")
    except (OSError, subprocess.SubprocessError):
        pass
    if not name:
        cfg = configparser.ConfigParser()
        cfg.read(GTK_INI)
        name = cfg.get("Settings", "gtk-font-name", fallback="")
    # "Adwaita Sans 11", "Inter Medium 10.5": drop the size and a style word.
    family = re.sub(r"(\s+(Bold|Medium|Light|Regular|Italic))*\s+[\d.]+$", "", name).strip()
    FONT_CACHE.update(at=now, family=family)
    return family


def palette():
    with open(THEME, "rb") as fh:
        data = tomllib.load(fh)
    mode = data.pop("mode", "dark")
    return {
        "mode": mode,
        "mtime": int(os.path.getmtime(THEME)),
        "font": ui_font(),
        "colors": {k: v for k, v in data.items() if isinstance(v, str)},
    }


class Handler(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def do_GET(self):
        route = self.path.split("?")[0]
        STATS["last"] = time.strftime("%H:%M:%S")
        STATS["theme" if route == "/theme.json"
              else "script" if route in SCRIPT_ROUTES
              else "other"] += 1

        if route == "/stats":
            body = json.dumps(STATS).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)
            return

        # Serving the script itself lets it carry an @updateURL pointing here,
        # so edits to the working copy reach the browser through the userscript
        # manager's own update check — no re-pasting, and no repo needed.
        if route in SCRIPT_ROUTES:
            try:
                with open(SCRIPT, "rb") as fh:
                    body = fh.read()
            except OSError as exc:
                self.send_error(404, explain=str(exc))
                return
            self.send_response(200)
            self.send_header("Content-Type", "text/javascript; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)
            return

        if route != "/theme.json":
            self.send_error(404)
            return
        try:
            body = json.dumps(palette()).encode()
        except (OSError, tomllib.TOMLDecodeError) as exc:
            self.send_error(500, explain=str(exc))
            return
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        # Harmless here, and lets a plain fetch() work if a future OWA
        # CSP ever permits it. GM_xmlhttpRequest ignores CORS anyway.
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass  # journald doesn't need a line per poll


if __name__ == "__main__":
    http.server.ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()
